server {
    listen 80;
    server_name aidoc.kro.kr;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name aidoc.kro.kr;

    ssl_certificate     /etc/letsencrypt/live/aidoc.kro.kr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aidoc.kro.kr/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 10M;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
    gzip_min_length 1000;
    gzip_comp_level 6;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://backend:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout    180s;
        proxy_send_timeout    180s;
        proxy_connect_timeout  60s;
        client_max_body_size  10M;
    }
}